
all: portfolio-large/3.png portfolio-large/4.png portfolio-large/5.png
	
	./guetzli --verbose --quality 84 portfolio-large/3.png portfolio/3.jpg
	./guetzli --verbose --quality 84 portfolio-large/4.png portfolio/4.jpg
	./guetzli --verbose --quality 84 portfolio-large/5.png portfolio/5.jpg
